#-- Lattice Semiconductor Corporation Ltd.
#-- Place & Route run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation}]} {
  file mkdir {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation}
}
cd {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation}

sys_set_attribute -gui on -msg {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/promote.xml}
msg_load {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/promote.xml}
des_set_project_udb -in {lab1_ai_proto_jl_implementation_map.udb} -out {lab1_ai_proto_jl_implementation.udb} -milestone par -pm ice40tp
des_set_reference_udb -clean
# par option
par_set_option { disable_timing_driven false placement_iterations 1 placement_iteration_start_point 1 placement_save_best_run "1"  number_of_host_machine_cores "1" path_based_placement on  stop_once_timing_is_met false   set_speed_grade_for_hold_optimization m disable_auto_hold_timing_correction false prioritize_hold_correction_over_setup_performance false run_placement_only false impose_hold_timing_correction false}
# run place & route
par_run
# backup netlist & constraint file
if {[file exists {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation_syn.udb}] && [file exists {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation_map.udb}] && [file exists {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation.udb}]} {
  file delete -force {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/lab1_ai_proto_jl_implementation_syn.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/lab1_ai_proto_jl_implementation_map.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/lab1_ai_proto_jl_implementation.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/lastrun.pdc}
  file copy -force -- {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation_syn.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/postsyn.udb}
  file copy -force -- {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation_map.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/postmap.udb}
  file copy -force -- {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/lab1_ai_proto_jl_implementation.udb} {C:/Users/jesli/Documents/GitHub/e155-lab1/AI_Prototype/lab1_ai_proto_jl/implementation/incr/postpar.udb}
}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
